SELECT
  TBLCLIENTS.CliNum,
  TBLCLIENTS.CliCode,
  TBLCLIENTS.CliNom,
  TBLCLIENTS.CliPrenom,
  TBLCLIENTSCONTRATS.CliConNum,
  TBLCLIENTSCONTRATS.CliConDateDebut,
  TBLCLIENTSCONTRATS.CliConDateFin,
  TBLCLIENTSCONTRATS.CliConDatePaiment,
  TBLCLIENTSCONTRATS.CliConType,
  TBLCLIENTSCONTRATS.CliConCoefficient,
  TBLCLIENTSCONTRATS.CliConPrixHT,
  TBLCLIENTSCONTRATS.CliConTVA,
  TBLCLIENTSCONTRATS.CliConPrix,
  TBLCLIENTSCONTRATS.CliConActif
FROM
  TBLCLIENTS
  INNER JOIN TBLCLIENTSCONTRATS ON TBLCLIENTS.CliNum = TBLCLIENTSCONTRATS.CliConCliNum
ORDER BY
  TBLCLIENTS.CliCode,
  TBLCLIENTSCONTRATS.CliConActif,
  [CliConDateFin] - Date() DESC;
