SELECT
  TBLCLIENTS.CliNum,
  TBLCLIENTS.CliCode,
  TBLCLIENTS.CliNom,
  TBLCLIENTS.CliPrenom,
  TBLCLIENTSCHAUDIERES.CliChdRef,
  TBLCLIENTSCHAUDIERES.CliChdDateServ,
  TBLCLIENTSCHAUDIERES.CliChdGaz,
  TBLCLIENTSCHAUDIERES.CliChdIdentification,
  TBLCLIENTSCHAUDIERES.CliChdMarque,
  TBLCLIENTSCHAUDIERES.CliChdPuissance,
  TBLCLIENTSCHAUDIERES.CliChdRemarque,
  TBLCLIENTSCHAUDIERES.CliChdActif
FROM
  TBLCLIENTS
  INNER JOIN TBLCLIENTSCHAUDIERES ON TBLCLIENTS.CliNum = TBLCLIENTSCHAUDIERES.CliChdCliNum
ORDER BY
  TBLCLIENTSCHAUDIERES.CliChdRef,
  TBLCLIENTSCHAUDIERES.CliChdActif,
  TBLCLIENTSCHAUDIERES.CliChdDateServ DESC;
