SELECT
  TBLCLIENTS.CliNum,
  TBLCLIENTS.CliCode,
  TBLCLIENTS.CliNom,
  TBLCLIENTS.CliPrenom,
  TBLCHAUDIERESINTERVENTIONS.ChdIntDate,
  TBLCHAUDIERESINTERVENTIONS.ChdIntNumero,
  TBLCHAUDIERESINTERVENTIONS.ChdIntType,
  TBLCHAUDIERESINTERVENTIONS.ChdIntDescription,
  TBLCHAUDIERESINTERVENTIONS.ChdIntNote
FROM
  TBLCLIENTS
  INNER JOIN (
    TBLCLIENTSCHAUDIERES
    INNER JOIN TBLCHAUDIERESINTERVENTIONS ON TBLCLIENTSCHAUDIERES.CliChdNum = TBLCHAUDIERESINTERVENTIONS.ChdIntCliChdNum
  ) ON TBLCLIENTS.CliNum = TBLCLIENTSCHAUDIERES.CliChdCliNum
ORDER BY
  TBLCHAUDIERESINTERVENTIONS.ChdIntDate DESC,
  TBLCHAUDIERESINTERVENTIONS.ChdIntNumero DESC;
